spring:
  main:
    banner-mode: "off"
  application:
    name=fix.autotest
  config:
    activate:
      on-profile: default

app-cfg:
  default_fix_values:
    security: ABC
    price: 100.99
    priceType: 1
    orderType: 2
  timeout_in_millisecond: 1000
  retry_count: 10


quickfix-cfg:
  initiator-cfg: ${user.dir}/config/initiator/quickfix-default.cfg
  exchange-sim-cfg: ${user.dir}/config/acceptor/quickfix-exchange-simulator-default.cfg

cucumber-cfg:
  cl_ord_id_prefix: samo
  timeout_in_sec: 60
  retry_count: 10

